// Vendored from rit3zh/expo-dynamic-notifications @ 5de059a (MIT License). Imports rewritten from @/ alias to relative paths.
const ISLAND_WIDTH = 126;
const ISLAND_HEIGHT = 37.33;
const ISLAND_TOP = 11;
const ISLAND_MIN_TOP = 12;
const CARD_MAX_WIDTH = 396;
const CARD_HEIGHT = 74;
const CARD_MARGIN = 16;
const CARD_GAP = 34;
const CARD_RADIUS = 26;
const DROP_SIZE = 52;
const NECK_WIDTH = 60;
const CANVAS_PADDING = 96;
const EDGE_MARGIN = 10;
const GOO_STRENGTH = 0.72;
const GOO_BLUR_MIN = 6;
const GOO_BLUR_MAX = 22;
const GOO_GAIN = 24;
const GOO_THRESHOLD = 0.42;
const GOO_INSET_RATIO = 0.26;
const DROP_GROW_SPAN = 0.75;
const DROP_GROW_POWER = 1.2;
const DROP_STRETCH = 0.45;
const EXIT_ANTICIPATION_VELOCITY = -0.6;
const NECK_BREAK = 0.82;
const NECK_RISE = 1.6;
const NECK_FALL = 1.4;
const DROP_TINT_START = 0.0;
const DROP_TINT_END = 0.7;
const CONTENT_MIN_SCALE = 0.92;
const BLUR_INTENSITY = 64;
const SHADOW_DY = 10;
const SHADOW_BLUR = 16;
// Staggered entry and exit timings - slow, luxurious fluid dynamic goo drop and morph (no dead slab)
const ENTER_TINT_DELAY = 80;
const ENTER_EXPAND_DELAY = 220;
const ENTER_REVEAL_DELAY = 300;
const EXIT_COLLAPSE_DELAY = 80;
const EXIT_DROP_DELAY = 260;
const AUTO_DISMISS = 6000;
const SWIPE_DISTANCE = -18;
const SWIPE_VELOCITY = -420;
const ENTRY_DURATION_MS = 1100;
const EXIT_DURATION_MS = 750;
const SPECULAR_RIM_FADE_IN_MS = 120;

// Shared glass, ink, and body transition ramp thresholds
const GLASS_IN_START = 0.4;    // surface appears under the droplet…
const GLASS_IN_END = 0.6;      // …fully in by 60% width (goo hands off)
const INK_CLEAR_START = 0.35;  // black starts clearing…
const INK_CLEAR_END = 0.95;    // …clear by 95% width
const BODY_START = 0.9;        // text and rim wait for 90% width

export {
  AUTO_DISMISS,
  BLUR_INTENSITY,
  BODY_START,
  CANVAS_PADDING,
  CARD_GAP,
  CARD_HEIGHT,
  CARD_MARGIN,
  CARD_MAX_WIDTH,
  CARD_RADIUS,
  CONTENT_MIN_SCALE,
  DROP_GROW_POWER,
  DROP_GROW_SPAN,
  DROP_SIZE,
  DROP_STRETCH,
  DROP_TINT_END,
  DROP_TINT_START,
  EDGE_MARGIN,
  ENTER_EXPAND_DELAY,
  ENTER_REVEAL_DELAY,
  ENTER_TINT_DELAY,
  EXIT_ANTICIPATION_VELOCITY,
  EXIT_COLLAPSE_DELAY,
  EXIT_DROP_DELAY,
  ENTRY_DURATION_MS,
  EXIT_DURATION_MS,
  GLASS_IN_END,
  GLASS_IN_START,
  GOO_BLUR_MAX,
  GOO_BLUR_MIN,
  GOO_GAIN,
  GOO_INSET_RATIO,
  GOO_STRENGTH,
  GOO_THRESHOLD,
  INK_CLEAR_END,
  INK_CLEAR_START,
  ISLAND_HEIGHT,
  ISLAND_MIN_TOP,
  ISLAND_TOP,
  ISLAND_WIDTH,
  NECK_BREAK,
  NECK_FALL,
  NECK_RISE,
  NECK_WIDTH,
  SHADOW_BLUR,
  SHADOW_DY,
  SPECULAR_RIM_FADE_IN_MS,
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
};

export default {
  AUTO_DISMISS,
  BLUR_INTENSITY,
  BODY_START,
  CANVAS_PADDING,
  CARD_GAP,
  CARD_HEIGHT,
  CARD_MARGIN,
  CARD_MAX_WIDTH,
  CARD_RADIUS,
  CONTENT_MIN_SCALE,
  DROP_GROW_POWER,
  DROP_GROW_SPAN,
  DROP_SIZE,
  DROP_STRETCH,
  DROP_TINT_END,
  DROP_TINT_START,
  EDGE_MARGIN,
  ENTER_EXPAND_DELAY,
  ENTER_REVEAL_DELAY,
  ENTER_TINT_DELAY,
  EXIT_ANTICIPATION_VELOCITY,
  EXIT_COLLAPSE_DELAY,
  EXIT_DROP_DELAY,
  ENTRY_DURATION_MS,
  EXIT_DURATION_MS,
  GLASS_IN_END,
  GLASS_IN_START,
  GOO_BLUR_MAX,
  GOO_BLUR_MIN,
  GOO_GAIN,
  GOO_INSET_RATIO,
  GOO_STRENGTH,
  GOO_THRESHOLD,
  INK_CLEAR_END,
  INK_CLEAR_START,
  ISLAND_HEIGHT,
  ISLAND_MIN_TOP,
  ISLAND_TOP,
  ISLAND_WIDTH,
  NECK_BREAK,
  NECK_FALL,
  NECK_RISE,
  NECK_WIDTH,
  SHADOW_BLUR,
  SHADOW_DY,
  SPECULAR_RIM_FADE_IN_MS,
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
};

