// Vendored from rit3zh/expo-dynamic-notifications @ 5de059a (MIT License). Imports rewritten from @/ alias to relative paths.
const ISLAND_WIDTH = 126;
const ISLAND_HEIGHT = 37.33;
const ISLAND_TOP = 11;
const ISLAND_MIN_TOP = 12;
const CARD_MAX_WIDTH = 396;
const CARD_HEIGHT = 74;
const CARD_MARGIN = 16;
const CARD_GAP = 34;
const DROP_SIZE = 52;
const NECK_WIDTH = 60;
const CANVAS_PADDING = 96;
const EDGE_MARGIN = 10;
const GOO_STRENGTH = 0.62;
const GOO_BLUR_MIN = 5;
const GOO_BLUR_MAX = 20;
const GOO_GAIN = 22;
const GOO_THRESHOLD = 0.43;
const GOO_INSET_RATIO = 0.26;
const DROP_GROW_SPAN = 0.7;
const DROP_GROW_POWER = 1.25;
const DROP_STRETCH = 0.38;
const EXIT_ANTICIPATION_VELOCITY = 2;
const NECK_BREAK = 0.82;
const NECK_RISE = 1.6;
const NECK_FALL = 1.4;
const DROP_TINT_START = 0.06;
const DROP_TINT_END = 0.88;
const CONTENT_MIN_SCALE = 0.88;
const BLUR_INTENSITY = 64;
const SHADOW_DY = 10;
const SHADOW_BLUR = 14;
const ENTER_TINT_DELAY = 110;
const ENTER_EXPAND_DELAY = 340;
const ENTER_REVEAL_DELAY = 560;
const EXIT_COLLAPSE_DELAY = 100;
const EXIT_DROP_DELAY = 280;
const AUTO_DISMISS = 3600;
const SWIPE_DISTANCE = -18;
const SWIPE_VELOCITY = -420;

export {
  AUTO_DISMISS,
  BLUR_INTENSITY,
  CANVAS_PADDING,
  CARD_GAP,
  CARD_HEIGHT,
  CARD_MARGIN,
  CARD_MAX_WIDTH,
  CONTENT_MIN_SCALE,
  DROP_GROW_POWER,
  DROP_GROW_SPAN,
  DROP_SIZE,
  DROP_STRETCH,
  DROP_TINT_END,
  DROP_TINT_START,
  EDGE_MARGIN,
  ENTER_EXPAND_DELAY,
  ENTER_REVEAL_DELAY,
  ENTER_TINT_DELAY,
  EXIT_ANTICIPATION_VELOCITY,
  EXIT_COLLAPSE_DELAY,
  EXIT_DROP_DELAY,
  GOO_BLUR_MAX,
  GOO_BLUR_MIN,
  GOO_GAIN,
  GOO_INSET_RATIO,
  GOO_STRENGTH,
  GOO_THRESHOLD,
  ISLAND_HEIGHT,
  ISLAND_MIN_TOP,
  ISLAND_TOP,
  ISLAND_WIDTH,
  NECK_BREAK,
  NECK_FALL,
  NECK_RISE,
  NECK_WIDTH,
  SHADOW_BLUR,
  SHADOW_DY,
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
};

export default {
  AUTO_DISMISS,
  BLUR_INTENSITY,
  CANVAS_PADDING,
  CARD_GAP,
  CARD_HEIGHT,
  CARD_MARGIN,
  CARD_MAX_WIDTH,
  CONTENT_MIN_SCALE,
  DROP_GROW_POWER,
  DROP_GROW_SPAN,
  DROP_SIZE,
  DROP_STRETCH,
  DROP_TINT_END,
  DROP_TINT_START,
  EDGE_MARGIN,
  ENTER_EXPAND_DELAY,
  ENTER_REVEAL_DELAY,
  ENTER_TINT_DELAY,
  EXIT_ANTICIPATION_VELOCITY,
  EXIT_COLLAPSE_DELAY,
  EXIT_DROP_DELAY,
  GOO_BLUR_MAX,
  GOO_BLUR_MIN,
  GOO_GAIN,
  GOO_INSET_RATIO,
  GOO_STRENGTH,
  GOO_THRESHOLD,
  ISLAND_HEIGHT,
  ISLAND_MIN_TOP,
  ISLAND_TOP,
  ISLAND_WIDTH,
  NECK_BREAK,
  NECK_FALL,
  NECK_RISE,
  NECK_WIDTH,
  SHADOW_BLUR,
  SHADOW_DY,
  SWIPE_DISTANCE,
  SWIPE_VELOCITY,
};
